  apiVersion: postgresql.cnpg.io/v1
  kind: Cluster
  metadata:
    name: postgres
    namespace: kroknes-psql
  spec:
    instances: 2
    bootstrap:
      initdb:
        database: postgres
        owner: postgres
    enableSuperuserAccess: true

    postgresql:
      parameters:
        auto_explain.log_min_duration: "10s"
        pg_stat_statements.max: "10000"
        pg_stat_statements.track: "all"
        shared_buffers: "256MB"
      pg_hba:
        - "host all all 10.244.0.0/16 md5"

    primaryUpdateStrategy: unsupervised
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: "1"
        memory: 512Mi
    startDelay: 300
    stopDelay: 300
    storage:
      size: 10Gi
